### ISSUE TITLE
Authentication error but missing config.json

### ISSUE THREAD

**Issue by SuperKooks** [b1naryth1ef/disco#112]
Disco gives me an authentication error when I try to load the configuration from a non-existent file. This should be changed into a files missing error.

**Comment by b1naryth1ef** [comment]
Unable to repro this;

```
(disco) [andrei@oaf:~/code/python/disco]$ python -m disco.cli --config lol.json
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/andrei/code/python/disco/disco/cli.py", line 110, in <module>
    disco_main(True)
  File "/home/andrei/code/python/disco/disco/cli.py", line 67, in disco_main
    config = ClientConfig.from_file(args.config)
  File "disco/util/config.py", line 23, in from_file
    with open(path, 'r') as f:
IOError: [Errno 2] No such file or directory: 'lol.json'
```

This seems like the correct error message. Can you please provide more details?
