### ISSUE TITLE
OSError with music example bot when requesting to play an url.

### ISSUE THREAD

**Issue by pimreijersen** [b1naryth1ef/disco#120]
Unable to play sound from a Youtube url with the music bot that comes as an example bot. Installed disco on a clean Debian image.
**OS Version**
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.7 (stretch)
Release:	9.7
Codename:	stretch
```
**Installation**
```
sudo pip install disco-py
sudo pip install disco-py[voice]
sudo pip install disco-py[music]
sudo pip install disco-py[performance]
```
**Commands**
The following commands are executed in discord.
```
@testbot join
@testbot play https://www.youtube.com/watch?v=pvT7mDwZ7Hw
```
**Log**
```
[INFO] 2019-01-31 14:50:09,388 - Bot:485 - Adding plugin module at path "music"
[INFO] 2019-01-31 14:50:09,530 - HTTPClient:271 - GET https://discordapp.com/api/v7/gateway (None)
[INFO] 2019-01-31 14:50:09,782 - GatewayClient:147 - Opening websocket connection to URL `wss://gateway.discord.gg?v=6&encoding=json&compress=zlib-stream`
[INFO] 2019-01-31 14:50:10,042 - GatewayClient:212 - WS Opened: sending identify payload
[INFO] 2019-01-31 14:50:10,043 - GatewayClient:122 - Received HELLO, starting heartbeater...
[INFO] 2019-01-31 14:50:10,173 - GatewayClient:126 - Received READY
[INFO] 2019-01-31 14:50:27,891 - VoiceClient:178 - [<VoiceClient #Entertainment #4>] Recieved VOICE_SERVER_UPDATE (state = awaiting_endpoint / endpoint = eu-central974.discord.gg:80)
[INFO] 2019-01-31 14:50:27,982 - VoiceClient:117 - [<VoiceClient #Entertainment #4>] Recieved Voice HELLO payload, starting heartbeater
[INFO] 2019-01-31 14:50:27,987 - VoiceClient:122 - [<VoiceClient #Entertainment #4>] Recived Voice READY payload, attempting to negotiate voice connection w/ remote
[INFO] 2019-01-31 14:50:28,000 - VoiceClient:159 - [<VoiceClient #Entertainment #4>] Recieved session description, connection completed
[youtube] pvT7mDwZ7Hw: Downloading webpage
[youtube] pvT7mDwZ7Hw: Downloading video info webpage
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/disco/voice/playable.py", line 213, in _encoder_loop
    raw = self.source.read(self.frame_size)
  File "/usr/local/lib/python2.7/dist-packages/disco/voice/playable.py", line 114, in read
    data, _ = self.proc.communicate()
  File "/usr/local/lib/python2.7/dist-packages/disco/voice/playable.py", line 144, in proc
    self._proc = subprocess.Popen(args, stdin=None, stdout=subprocess.PIPE)
  File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 585, in __init__
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 554, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 1312, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Thu Jan 31 14:50:42 2019 <Greenlet at 0x7f25204cab90: <bound method BufferedOpusEncoderPlayable._encoder_loop of <disco.voice.playable.BufferedOpusEncoderPlayable object at 0x7f251edd5440>>> failed with OSError
```

**Comment by b1naryth1ef** [comment]
You need ffmpeg (e.g. avconv) installed on the system.

**Comment by b1naryth1ef** [comment]
You can also alter the command used here; https://github.com/b1naryth1ef/disco/blob/ec7f0797a9c11deb02a1c1e11a66436bcb5acce0/disco/voice/playable.py#L98
