### ISSUE TITLE
TypeError on update_prescence()

### ISSUE THREAD

**Issue by JamsNJellies** [b1naryth1ef/disco#121]
Not sure if I am just being dumb here but no matter how I pass the GameType to the game object it gives an error similar to the one below
```
Traceback (most recent call last):
  File "/home/james/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/james/.local/lib/python2.7/site-packages/holster/emitter.py", line 72, in __call__
    return self.callback(*args, **kwargs)
  File "/home/james/.local/lib/python2.7/site-packages/disco/bot/plugin.py", line 335, in dispatch
    result = func(event, *args, **kwargs)
  File "plugins/events.py", line 9, in on_ready
    self.client.update_presence(self, 'ONLINE', user.Game(GameType.LISTENING.value, "for ;help"))
  File "/home/james/.local/lib/python2.7/site-packages/disco/types/base.py", line 321, in __init__
    self.load(obj, **kwargs)
  File "/home/james/.local/lib/python2.7/site-packages/disco/types/base.py", line 336, in load
    return self.load_into(self, *args, **kwargs)
  File "/home/james/.local/lib/python2.7/site-packages/disco/types/base.py", line 342, in load_into
    raw = obj[field.src_name]
TypeError: 'int' object has no attribute '__getitem__'
```
And my code looks like this:
```
from disco.bot import Bot, Plugin
from disco.types import user
from disco.types.user import GameType

class EventsPlugin(Plugin):
    @Plugin.listen('Ready')
    def on_ready(self, event):
        print(GameType.LISTENING.value)
        self.client.update_presence(self, 'ONLINE', user.Game(GameType.LISTENING.value, "for ;help"))

```

**Comment by juanmuscaria** [comment]
Try this:
 `self.client.update_presence(Status.online, Game(type=GameType.LISTENING, name="for ;help"))`

**Comment by JamsNJellies** [comment]
> Try this:
> `self.client.update_presence(Status.online, Game(type=GameType.LISTENING, name="for ;help"))`
That gives this error:
```
Traceback (most recent call last):
  File "/home/james/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/james/.local/lib/python2.7/site-packages/holster/emitter.py", line 72, in __call__
    return self.callback(*args, **kwargs)
  File "/home/james/.local/lib/python2.7/site-packages/disco/bot/plugin.py", line 335, in dispatch
    result = func(event, *args, **kwargs)
  File "plugins/events.py", line 9, in on_ready
    self.client.update_presence(self, Status.ONLINE, user.Game(type=GameType.LISTENING, name="for ;help"))
  File "/home/james/.local/lib/python2.7/site-packages/disco/client.py", line 127, in update_presence
    raise TypeError('Game must be a Game model')
TypeError: Game must be a Game model
Sat Feb  9 14:09:45 2019 <Greenlet at 0x7f0fe82c49b0: <holster.emitter.EmitterSubscription object at 0x7f0fe8314dd0>(<disco.gateway.events.Ready object at 0x7f0fe828cd)> failed with TypeError
```

**Comment by juanmuscaria** [comment]
```
from disco.bot import *
from disco.types.user import Status, Game, GameType


class EventsPlugin(Plugin):
    @Plugin.listen('Ready')
    def on_ready(self, event):
        self.client.update_presence(Status.online, Game(type=GameType.LISTENING, name="for ;help"))
```

**Comment by JamsNJellies** [comment]
Thanks that works fine
