### ISSUE TITLE
TypeError when passing youtubedl bufferedopus object through to player

### ISSUE THREAD

**Issue by LMByrne** [b1naryth1ef/disco#134]
When using a voice system similar to the [examples ](https://github.com/b1naryth1ef/disco/blob/master/examples/music.py), Disco's voice been throwing the exception for me below since what I suspect was #130.
```Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.6/dist-packages/disco/voice/playable.py", line 213, in _encoder_loop
    raw = self.source.read(self.frame_size)
  File "/usr/local/lib/python3.6/dist-packages/disco/voice/playable.py", line 115, in read
    self._buffer = BufferedIO(data)
TypeError: initial_value must be str or None, not bytes
2019-04-06T13:49:19Z <Greenlet "Greenlet-0" at 0x7efcbfbcc548: <bound method BufferedOpusEncoderPlayable._encoder_loop of <disco.voice.playable.BufferedOpusEncoderPlayable object at 0x7efcbe91c348>>> failed with TypeError```

**Comment by OGNova** [comment]
Hey there, can we see the code that you're using to play music? You say similar, how similar?

**Comment by LMByrne** [comment]
The only real difference is that I have ``YoutubeDLInput(video_url, command="ffmpeg")`` which has worked previously (apart from that it only differs in how it handle's the ytdl object before it's added it to the player's queue and a slightly different join system). I tried using the sample code as a reference (with the only change being command="ffmpeg") and got the same exception.

**Comment by b1naryth1ef** [comment]
v1.0.0 of disco which should have a early alpha or beta release in the next few weeks will be completely changing how voice works (in an entirely backwards-incompatible way). Due to this I'm not going to accept and reports around the current voice functionality.
