### ISSUE TITLE
error when running in Python 2.7

### ISSUE THREAD

**Issue by A5rocks** [b1naryth1ef/disco#164]
```
[INFO] 2019-11-05 06:41:24,025 - HTTPClient:272 - GET https://discordapp.com/api/v7/gateway (None)
[INFO] 2019-11-05 06:41:24,080 - GatewayClient:148 - Opening websocket connection to URL `wss://gateway.discord.gg?v=6&encoding=json&compress=zlib-stream`
[INFO] 2019-11-05 06:41:24,153 - GatewayClient:213 - WS Opened: sending identify payload
[INFO] 2019-11-05 06:41:24,155 - GatewayClient:123 - Received HELLO, starting heartbeater...
[INFO] 2019-11-05 06:41:25,591 - GatewayClient:127 - Received READY
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "build/bdist.linux-x86_64/egg/disco/util/emitter.py", line 77, in __call__
    return self.callback(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/disco/gateway/client.py", line 99, in handle_dispatch
    obj = GatewayEvent.from_dispatch(self.client, packet)
  File "build/bdist.linux-x86_64/egg/disco/gateway/events.py", line 42, in from_dispatch
    raise Exception('Could not find cls for {} ({})'.format(data['t'], data))
Exception: Could not find cls for PRESENCES_REPLACE ({u'd': [], u's': 4, u't': u'PRESENCES_REPLACE', u'op': 0})
2019-11-04T21:41:26Z <Greenlet "Greenlet-0" at 0x7f758d4c2998: <disco.util.emitter.EmitterSubscription object at 0x7f758d51efd0>({u'd': [], u's': 4, u't': u'PRESENCES_REPLACE', u')> failed with Exception
```

I got this error somehow. Running `python2.7` with the `staging/v1.0.0` branch. I reran the same command over and over afterwards, but didn't get this error again.

**Comment by b1naryth1ef** [comment]
Its not an error so much as a warning. Discord sends this undocumented payload in various scenarios, but especially during issues on their end. I'd just ignore it.
