### ISSUE TITLE
append new events

### ISSUE THREAD

**Issue by re1ard** [b1naryth1ef/disco#184]
error #1:
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.6/dist-packages/holster-2.0.0-py3.6.egg/holster/emitter.py", line 72, in __call__
    return self.callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/disco_py-0.0.13rc2-py3.6.egg/disco/gateway/client.py", line 98, in handle_dispatch
    obj = GatewayEvent.from_dispatch(self.client, packet)
  File "/usr/local/lib/python3.6/dist-packages/disco_py-0.0.13rc2-py3.6.egg/disco/gateway/events.py", line 42, in from_dispatch
    raise Exception('Could not find cls for {} ({})'.format(data['t'], data))
Exception: Could not find cls for INVITE_CREATE ({'t': 'INVITE_CREATE', 's': 28832, 'op': 0, 'd': {'uses': 0, 'temporary': False, 'max_uses': 0, 'max_age': 86400, 'inviter': {'username': '', 'public_flags': 256, 'id': '', 'discriminator': '', 'avatar': ''}, 'guild_id': '', 'created_at': '2020-10-29T19:12:54.952213+00:00', 'code': '', 'channel_id': ''}})
2020-10-29T19:12:55Z <Greenlet at 0x7fa971a76848: <holster.emitter.EmitterSubscription object at 0x7fa9b597ae10>({'t': 'INVITE_CREATE', 's': 28832, 'op': 0, 'd': {)> failed with Exception

error #2:
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.6/dist-packages/holster-2.0.0-py3.6.egg/holster/emitter.py", line 72, in __call__
    return self.callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/disco_py-0.0.13rc2-py3.6.egg/disco/gateway/client.py", line 98, in handle_dispatch
    obj = GatewayEvent.from_dispatch(self.client, packet)
  File "/usr/local/lib/python3.6/dist-packages/disco_py-0.0.13rc2-py3.6.egg/disco/gateway/events.py", line 42, in from_dispatch
    raise Exception('Could not find cls for {} ({})'.format(data['t'], data))
Exception: Could not find cls for INTEGRATION_UPDATE ({'t': 'INTEGRATION_UPDATE', 's': 27748, 'op': 0, 'd': {'user': {'username': '', 'public_flags': 64, 'id': '', 'discriminator': '8717', 'avatar': ''}, 'type': 'twitch', 'syncing': False, 'synced_at': '2020-10-29T19:00:32.667662+00:00', 'subscriber_count': 1, 'role_id': '', 'revoked': False, 'name': '', 'id': '', 'expire_grace_period': 1, 'expire_behavior': 0, 'enabled': True, 'enable_emoticons': True, 'account': {'name': 'nymi_', 'id': ''}, 'guild_id': ''}})
2020-10-29T19:00:32Z <Greenlet at 0x7fa973dbbb48: <holster.emitter.EmitterSubscription object at 0x7fa9b597ae10>({'t': 'INTEGRATION_UPDATE', 's': 27748, 'op': 0, ')> failed with Exception

error #3:
not available event INVITE_DELETE

**Comment by re1ard** [comment]
plus voice error:
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.6/dist-packages/holster-2.0.0-py3.6.egg/holster/emitter.py", line 72, in __call__
    return self.callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/disco_py-0.0.13rc2-py3.6.egg/disco/voice/client.py", line 238, in on_voice_codecs
    self.transport_id = data['media_session_id']
KeyError: 'media_session_id'
2020-10-29T18:17:38Z <Greenlet at 0x7fa973e1f748: <holster.emitter.EmitterSubscription object at 0x7fa9729d5d68>({'video_codec': None, 'audio_codec': 'opus'})> failed with KeyError

**Comment by b1naryth1ef** [comment]
Not even going to look at this since your just posting logs without any further information or code. Could not find cls errors are from unhandled events in the library, we do not support `INTEGRATION_UPDATE`. If you want to use that event or don't want the error you will have to make manual modifications to the library.

Voice support was never finalized and isn't supported as of the recent versions of the library. You should look into using something like lavalink or telecom.
