### ISSUE TITLE
Disco doesn't dance (fails on startup)

### ISSUE THREAD

**Issue by DocCodes** [b1naryth1ef/disco#72]
I receive an error when trying to start my bot, even if I empty out the bot entirely. I have verified there are no errors in my code and that my token is correct.

```
Traceback (most recent call last):
  File "C:\Users\evany\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\evany\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\evany\AppData\Local\Programs\Python\Python36-32\lib\site-packages\disco\cli.py", line 99, in <module>
    disco_main(True)
  File "C:\Users\evany\AppData\Local\Programs\Python\Python36-32\lib\site-packages\disco\cli.py", line 74, in disco_main
    client = Client(config)
  File "C:\Users\evany\AppData\Local\Programs\Python\Python36-32\lib\site-packages\disco\client.py", line 91, in __init__
    self.events = Emitter(gevent.spawn)
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by b1naryth1ef** [comment]
What version are you running?

**Comment by DocCodes** [comment]
Running `pip3 list` I can see that I am running `disco.py 0.0.11`

**Comment by DocCodes** [comment]
Rerunning `pip3 install disco-py -U` several packages were downgraded:
* `six`
* `holster`
* `requests`
* `websocket-client`
It's apparent to me that one of these causes an error is because after they were downgraded it worked. Installing each individually revealed that moving from `holster 1.0.16` to `holster 2.0.0` caused the issue.
